name: cd

on:
  workflow_run:
    workflows: ["test_and_check"]
    branches: [main]
    types:
      - completed

env:
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 18.12.1
  RAILS_ENV: test
  DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test_and_check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg ${{ env.RAILS_MASTER_KEY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}