name: ci

on: [push, pull_request]

env:
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 18.12.1
  RAILS_ENV: test
  DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

jobs:
  minitest_and_linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)

      - name: Bundle install
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle lock --add-platform x86_64-linux
          bundle install --jobs 4 --retry 3

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Yarn install
        run: yarn install --check-files

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run ESlint
        run: yarn run lint:eslint

      - name: Run Prettier
        run: yarn run lint:prettier

      - name: Run tests
        run: bundle exec rspec